server:
  port: 81
  servlet:
    context-path: /consumer
spring:
  application:
    name: serviceconsumer
    #consul??????
  cloud:
    consul:
      discovery:
        heartbeat:
          enabled: true
    port: 8500
    discover:
      service-name: ${spring.application.name}
